spec:
  template:
    spec:
      containers:
        - name: synapse
          volumeMounts:
            - name: extraconfig
#              mountPath: /synapse/config/conf.d/extraconfig/
              mountPath: /etc/matrix-synapse/conf.d/
      volumes:
        - configMap:
            name: matrix-synapse-extraconfig
          name: extraconfig