apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "{{ stunner.server_name }}"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: stunner-ingress
  namespace: stunner
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ stunner.server_name }}"
      http:
        paths:
          - backend:
              service:
                name: stunner
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - "{{ stunner.server_name }}"
      secretName: stunner-tls-secret
