---
- name: should the coturn server be activated or not?
  set_fact:
    stunner_absent_or_present: "{{ 'absent' if absent_or_present == 'absent' or not stunner.enabled else 'present' }}"

- name: Add stunner helm repository
  kubernetes.core.helm_repository:
    name: stunner
    repo_url: "https://l7mp.io/stunner"

- name: Deploy latest version of stunner control plane chart inside stunner-system namespace (and create it)
  kubernetes.core.helm:
    name: stunner-gateway-operator
    chart_ref: stunner/stunner-gateway-operator
    chart_version: "{{ stunner.chart_version }}"
    release_namespace: stunner-system
    create_namespace: true
    release_values:
      stunnerGatewayOperator.dataplane.mode: managed
    state: "{{ stunner_absent_or_present }}"

- name: Create or delete namespace dedicated to stunner
  kubernetes.core.k8s:
    name: stunner
    api_version: v1
    kind: Namespace
    state: "{{ stunner_absent_or_present }}"

- name: Create secret for stunner
  kubernetes.core.k8s:
    template: "stunner-auth-secret.yml"
    state: "{{ stunner_absent_or_present }}"

- name: Configure stunner
  when: stunner_absent_or_present == "present"
  kubernetes.core.k8s:
    template: "stunner-configuration.yml"

- name: Get Stunner gateway external IP
  when: stunner_absent_or_present == "present"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: udp-gateway
    namespace: stunner
  register: udp_gateway_service
  until: udp_gateway_service.resources[0].status.loadBalancer.ingress[0].ip is defined
  retries: 48
  delay: 5

- name: register Stunner gateway external IP
  when: stunner_absent_or_present == "present"
  set_fact:
    stunner_gateway_ip: "{{ udp_gateway_service.resources[0].status.loadBalancer.ingress[0].ip | default('no_stunner')}}"
