apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
data:
  synapse-db-password: "{{ matrix.db_password | b64encode}}"
  avnadmin-db-password: "{{ matrix.avnadmin_password | b64encode}}"
