---
- name: Install python dependencies with pip
  ansible.builtin.pip:
    name:
      - kubernetes
      - ovh
      - yq

- name: Check kubeconfig by getting cluster information
  kubernetes.core.k8s_cluster_info:
  register: api_status
