---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
data:
  password: "{{ keycloak.db_password | b64encode}}"
  username: "{{ keycloak.db_user | b64encode}}"
