apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matrix-servicemonitor
  namespace: monitoring
  labels:
    team: matrix-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
  endpoints:
    - port: metrics
  namespaceSelector:
    any: true
#spec:
#  selector:
#    matchLabels:
#      app.kubernetes.io/component: synapse
#      app.kubernetes.io/instance: matrix-synapse
#
#    matchExpressions:
#      - key: app.kubernetes.io/component
#        operator: NotIn
#        values:
#          - well-known
#          - master
#          - primary
#
#  namespaceSelector:
#    any: true
#
#  podMetricsEndpoints:
#    - port: metrics
#      path: /_synapse/metrics
#      relabelings:
#        # Set instance name
#        - sourceLabels:
#            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
#          separator: "/"
#          targetLabel: instance
#
#        # Set job to component name
#        - sourceLabels:
#            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
#            - __meta_kubernetes_pod_label_app_kubernetes_io_component
#          separator: "/"
#          targetLabel: job
#
#        # Set index to pod name
#        - sourceLabels:
#            - __meta_kubernetes_pod_name
#          targetLabel: index
