---
#
# Role used to initialise the postgresql database
# It is done with ansible because it is not possible to create a postgresql database
# on OVH with Terraform ovh provider while specifying a custom collate and c-type
#
- name: Postgres database secret for Synapse
  kubernetes.core.k8s:
    state: "{{ absent_or_present }}"
    template: "postgres-secret.yml"

- name: create configmap with initdb.sh script
  kubernetes.core.k8s:
    state: "{{ absent_or_present }}"
    template: "psql-configmap.yml"

- name: Run the initdb.sh with a dedicated job
  kubernetes.core.k8s:
    state: "{{ absent_or_present }}"
    template: "psql-initdb-job.yml"
