apiVersion: v1
kind: Service
metadata:
  labels:
    app: msteams-bridge
  name: msteams-svc
  namespace: msteams
spec:
  type: ClusterIP
  selector:
    app: msteams-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8432