---
- name: Add ingress-nginx helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: install ingress-nginx helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_controller.version }}"
    release_namespace: ingress-nginx
    create_namespace: true
    update_repo_cache: yes

- name: Get the ingress-controller external IP
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
  register: ingress_controller_service
  until: ingress_controller_service.resources[0].status.loadBalancer.ingress[0].ip is defined
  retries: 10
  delay: 10

- name: "DEBUG ingress-controller external IP"
  debug:
    msg: "{{ ingress_controller_service.resources[0].status.loadBalancer.ingress[0].ip }}"


- name: Create namespace dedicated to octavia-ingress-controller
  kubernetes.core.k8s:
    name: ingress-octavia
    api_version: v1
    kind: Namespace
    state: absent
#
#- name: Install octavia-ingress-controller configmap
#  kubernetes.core.k8s:
#    template: "octavia-ingress-controller-config.yml"
#
#- name: Add octavia-ingress-controller helm repository
#  kubernetes.core.helm_repository:
#    name: slamdev
#    repo_url: "https://slamdev.github.io/helm-charts"
#
#- name: install octavia-ingress-controller helm chart
#  kubernetes.core.helm:
#    name: octavia-ingress-controller
#    chart_ref: slamdev/octavia-ingress-controller
#    chart_version: "{{ ovh.octavia.ingress_controller.helm_version }}"
#    release_namespace: ingress-octavia
#    create_namespace: true
#    update_repo_cache: yes
#    release_values:
#      debug: true
#      ingressConfigVolume:
#        configMap:
#          name: octavia-ingress-controller-config
#          items:
#            - key: config
#              path: octavia-ingress-controller-config.yaml
