---
- name: Create namespace dedicated to external-dns
  kubernetes.core.k8s:
    name: external-dns
    api_version: v1
    kind: Namespace
    state: present

- name: Configure DNS with external-dns
  kubernetes.core.k8s:
    state: present
    template: 'external-dns.yml'