name: Security

on:
  workflow_dispatch:
  push:

jobs:
  kics-scan:
    name: "Scan IaC with kics"
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir

      - name: scan code with kics
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          path: .
          config_path: ./.github/kics.config.yml
          output_path: results-dir
          output_formats: "json,sarif"
          ignore_on_exit: "results"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif
